export {default as Login} from "./Login/Login"
export {default as Signup} from "./Signup/Signup"
export {default as MainPage} from "./MainPage/MainPage"
export {default as LandingPage} from "./LandingPage/LandingPage"
export {default as Cart} from "./Cart/Cart"
export {default as HomePage} from "./HomePage/HomePage"
export {default as LatestDeals} from "./LatestDeals/LatestDeals"
export {default as Profile} from "./Profile/Profile"
export {default as DetailPage}from "./DetailPage/DetailPage"
export {default as MobileOTP} from "./MobileOtp/MobileOTP"
export {default as OTPScreen} from "./MobileOtp/OTPScreen"
export {default as Search} from "./Search/Search"
export {default as Charts} from "./Charts/Charts"
export {default as NotificationsScreen} from "./NotificationsScreen/NotificationsScreen"