export default {profile:require('../assets/images/profile.jpeg'),
rightArrow:require('../assets/images/rightArrow.png'),
calenderImage:require('../assets/images/calenderImage.png'),
leftArrow:require('../assets/images/leftArrow.png'),
crossImage:require('../assets/images/crossImage.png'),
googleImage:require('../assets/images/google.png'),
facebookImage:require('../assets/images/facebook.png'),
carousal:require('../assets/images/carousal2.png'),
peanut:require('../assets/images/carousal3.png'),
nitro:require('../assets/images/carousal1.png'),
logo:require('../assets/images/logo.jpeg'),
myntra:require('../assets/images/myntraLogo.png'),
}