export default {

    LOGIN:'LOGIN',
    ADD_LIST : 'ADD',
    INCREMENT : 'INCREMENT',
    DECREMENT : 'DECREMENT',
    DELETE_LIST:'DELETE',
    LOGOUT:'LOGOUT',
    SWITCH_THEME:"SWITCH_THEME",
    INFINITE_LIST:"INFINITE_LIST",
}